server:
  port: 9010

 
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver  
  devtools:
    restart:
      enabled: true
  mvc:
    static-path-pattern: /static/**
  application:
    name: eurekaClient
    

    
mybatis:
  type-aliases-package: com.weizhe.eurekaClient.model
  
  
weizhe: 
  test: 2018

    

      
