server:
  port: 9010

 
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver  
  devtools:
    restart:
      enabled: true
  mvc:
    static-path-pattern: /static/**
  application:
    name: eurekaClient
  rabbitmq:
    host: 192.168.1.239
    port: 5672
    username: admin
    password: admin
  stream:
      bindings:
        inputMyMessage: 
          destination: myMessage
          group: test
          content-type: application/json
        outputMyMessage: 
          destination: myMessage
          group: test
          content-type: application/json
        inputTestMessage: 
          destination: testMessage
          group: test
        outputTestMessage: 
          destination: testMessage
          group: test
    

    
mybatis:
  type-aliases-package: com.weizhe.eurekaClient.model
  
  
weizhe: 
  test: 2015

    

      
